name: Manual Build - Flutter Nightly

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: "${{ inputs.upload-artifact }}"
      upload-tag: "${{ inputs.upload-tag }}"
